---
- name: Install PHP 5.4 on RHEL
  yum: name={{ item }} state=present
  with_items:
    - php54-cli 
    - php54-pecl-memcache 
    - php54-curl 
    - php54-gd 
    - php54-mysql 
    - php54-mcrypt 
    - php54-ioncube-loader
  when: ansible_os_family == "RedHat"
  notify: restart apache
  ignore_errors: True

- name: Install PHP 5 on Debian
  apt: name={{ item }} state=present
  with_items:
    - php5
    - php5-cli 
    - php5-memcache
    - php5-curl 
    - php5-gd 
    - php5-mysql 
    - php5-mcrypt 
  when: ansible_os_family == "Debian"
  notify: restart apache
  ignore_errors: True
